// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/client/consensus/grandpa (interfaces: ForkTree)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockForkTree is a mock of ForkTree interface.
type MockForkTree struct {
	ctrl     *gomock.Controller
	recorder *MockForkTreeMockRecorder
}

// MockForkTreeMockRecorder is the mock recorder for MockForkTree.
type MockForkTreeMockRecorder struct {
	mock *MockForkTree
}

// NewMockForkTree creates a new mock instance.
func NewMockForkTree(ctrl *gomock.Controller) *MockForkTree {
	mock := &MockForkTree{ctrl: ctrl}
	mock.recorder = &MockForkTreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForkTree) EXPECT() *MockForkTreeMockRecorder {
	return m.recorder
}
